Repository jtr13/cc19, pull requests merged in 2019-10, with the labels that each got.

#4 fix typo
  README.md
Labels: bug

#20 Hojin Lee and Hyuk Joon Kwon
  .travis.yml
  DESCRIPTION
  _bookdown.yml
  ridgeline_plot.Rmd
Labels: data viz (interactive), edav.info

#21 Create CC04-EDAV Community Contribution.Rmd
  bookdown.rmd
Labels: bug, workshop

#29 CartoDB tutorial (Luis Lu and Timothy Huang)
  _bookdown.yml
  carto_tutorial.Rmd
  resources/carto_tutorial/carto.png
Labels: tutorial

#30 Stamen Maps with ggmap
  .travis.yml
  DESCRIPTION
  _bookdown.yml
  maps.Rmd
  resources/ggmap/data/uscities.zip
Labels: data viz (static), edav.info

#36 Upload Notes_html_js_d3 from cc group 60
  Notes_html_js_d3.Rmd
  _bookdown.yml
Labels: cheat sheet, data viz (interactive)

#34 Shiny tutorial
  DESCRIPTION
  _bookdown.yml
  a_tutorial_of_shiny.Rmd
  resources/shiny_tutorial/.DS_Store
  resources/shiny_tutorial/box2.png
  resources/shiny_tutorial/button.png
  resources/shiny_tutorial/carsdata.png
  resources/shiny_tutorial/eventreactive.png
  resources/shiny_tutorial/hist.png
  resources/shiny_tutorial/hist1.png
  resources/shiny_tutorial/hist2.png
  resources/shiny_tutorial/newuserinstructions.png
  resources/shiny_tutorial/out.png
  resources/shiny_tutorial/reactive.png
  resources/shiny_tutorial/reactivevalue.png
  resources/shiny_tutorial/selectbox.png
  resources/shiny_tutorial/shinyapps.io.png
  resources/shiny_tutorial/slider.png
  resources/shiny_tutorial/sp1.png
  resources/shiny_tutorial/summary.png
  resources/shiny_tutorial/sumstats.png
  resources/shiny_tutorial/sumstats2.png
  resources/shiny_tutorial/value.png
Labels: bug, data viz (interactive), tutorial

#42 Add files via upload
  Leaflet_CheatSheet.Rmd
Labels: cheat sheet

#31 files from Tinder study
  DESCRIPTION
  _bookdown.yml
  resources/tinder_study/20160410_185359.jpg
  resources/tinder_study/20160413_201214.jpg
  resources/tinder_study/20170204_090225.jpg
  resources/tinder_study/bentinder.csv
  resources/tinder_study/tinder.png
  resources/tinder_study/tinder_example.jpg
  tinder_study.Rmd
Labels: Other, changes requested

#39 Wordcloud tutorial
  DESCRIPTION
  _bookdown.yml
  resources/wordcloud_tutorial/R.png
  resources/wordcloud_tutorial/bat.png
  wordcloud_tutorial.Rmd
Labels: tutorial

#79 Update tinder_study.Rmd
  tinder_study.Rmd
Labels: internal

#83 Translation master chapter
  _bookdown.yml
  master_translation.Rmd
Labels: internal

#80 CC40 Translation for visualization
  Translation_for_R_and_ggplot2_visualization.Rmd
Labels: translation

#37 R - package writing workshop tutorial with link to the pdf
  r-package-writing.Rmd
Labels: workshop

#27 Likert edav info
  .travis.yml
  DESCRIPTION
  _bookdown.yml
  likert_edav_info.Rmd
Labels: data viz (static), edav.info
