Repository jtr13/cc19, pull requests merged in 2019-11, with the labels that each got.

#88 bug fixed
  wordcloud_tutorial.Rmd
Labels: tutorial

#103 CC63: Initial version
  _bookdown.yml
  rstudio_vs_jupyterlab.Rmd
Labels: lightning talk

#107 Fluctuation Plots added
  DESCRIPTION
  FluctuationPlots.Rmd
  _bookdown.yml
Labels: data viz (static)

#73 ggmaps content modification
  maps.Rmd
Labels: maps

#130 add Hex Sticker rmd file
  _bookdown.yml
  hex_sticker.Rmd
Labels: Other

#112 Group38 Dplyr Relational Databases
  DESCRIPTION
  Dplyr_Relational_Databases.Rmd
  _bookdown.yml
  resources/group38/Key BIS (2).png
  resources/group38/Key BIS.png
  resources/group38/Relational Data Base.png
  resources/group38/Relational_model.png
  resources/group38/full_join.png
  resources/group38/inner_join.png
  resources/group38/joins.png
  resources/group38/left_join.png
  resources/group38/right_join.png
Labels: data wrangling

#148 Yihao Li(yl4326)'s submission, .DS_store removed
  DESCRIPTION
  Visualization_in_Time_Series_Analysis.Rmd
  _bookdown.yml
  resources/Visualization_in_Time_Series_Analysis/w-gs1yr.txt
Labels: data viz (static)

#69 Add gantt_chart.Rmd CC75
  DESCRIPTION
  _bookdown.yml
  gantt_chart.Rmd
Labels: bug, data viz (static)

#95 Submitting ice cream survey rmd file
  DESCRIPTION
  _bookdown.yml
  ice_cream_survey.Rmd
Labels: Data analysis

#102 Adding ggmosaic cheatsheet and translation for community contribution project
  DESCRIPTION
  _bookdown.yml
  ggmosaic_cheatsheet_translation.Rmd
Labels: cheat sheet, translation

#89 CC11 - List of contribution
  _bookdown.yml
  list_of_contribution.Rmd
Labels: Other

#85 add latex_visualization
  _bookdown.yml
  latex_visualization.Rmd
Labels: Other

#86 submission
  DESCRIPTION
  _bookdown.yml
  first_step_of_data_analysis.Rmd
Labels: bug, data wrangling

#111 cc_contribution Rmd file for multiclass_hexbins
  DESCRIPTION
  _bookdown.yml
  multiclass_hexbin.Rmd
Labels: bug, data viz (static)

#105 Upload cc39 project
  Stringr_introduction_chinese_version.Rmd
  _bookdown.yml
Labels: translation

#72 Edav flowchart
  _bookdown.yml
  edav_flowchart.Rmd
  resources/edav_flowchart/EDAV_CC_bx2147_ym2764.pdf
  resources/edav_flowchart/README.md
Labels: bug, cheat sheet

#109 continuous_variables_with_r_in_chinese
  _bookdown.yml
  continuous_variables_with_r_in_chinese.Rmd
Labels: translation

#115 Add a new file
  _bookdown.yml
  translation_visualising_spatial_data.Rmd
Labels: translation

#53 Matthew Mackenzie (mbm2228) cc2019 submission
  DESCRIPTION
  _bookdown.yml
  opencpu_tutorial.Rmd
Labels: Other, changes requested

#59 Zihe Wang and Yaotian Dai
  _bookdown.yml
  bokeh_cheatsheet.Rmd
Labels: cheat sheet

#54 data_structure_and_data_cleaning
  _bookdown.yml
  data_structure_and_data_cleaning_tutorial.Rmd
Labels: Other, bug

#45 group_43_submission
  Date_and_Time_Cheatsheet.Rmd
  _bookdown.yml
  resources/Date_and_Time_Cheatsheet/Date_and_Time_Cheatsheet.pdf
Labels: cheat sheet

#70 Add dataframe cheatsheet
  DESCRIPTION
  _bookdown.yml
  dataframe_cheatsheet.Rmd
Labels: cheat sheet

#127 create intro_to_ggparty branch
  DESCRIPTION
  _bookdown.yml
  intro_to_ggparty.Rmd
Labels: data viz (static)

#92 Visualization with GeomMLBStadiums
  Viz_with_GeomMLBStadiums.Rmd
  _bookdown.yml
Labels: data viz (static)

#117 Community contribution group 65 - Stocks analysis with plotly
  DESCRIPTION
  Stocks_analysis_with_plotly.Rmd
  _bookdown.yml
Labels: data viz (interactive)

#58 Time series cheatsheet
  _bookdown.yml
  resources/time_series_cheatsheet/README.md
  resources/time_series_cheatsheet/TimeSeriesCheatsheet.key
  resources/time_series_cheatsheet/TimeSeriesCheatsheet.pdf
  time_series_cheatsheet.Rmd
Labels: cheat sheet

#90 wordcloud2 cheat sheet
  _bookdown.yml
  wordcloud2_cheatsheet.Rmd
Labels: cheat sheet

#129 Add codes for tutorial on Stacked Bar Charts and Treemaps
  DESCRIPTION
  Stacked_Bar_Charts_and_Treemaps.Rmd
  _bookdown.yml
Labels: data viz (static)

#118 Submission for Likert VS Bar Charts for MathAnxiety Dataset: Group12
  .travis.yml
  Likert_vs_Bar_Chart.Rmd
  _bookdown.yml
Labels: data viz (static)

#52 likert_package_translate
  _bookdown.yml
  likert_package_translate.Rmd
Labels: translation

#116 Nullabor translation v2
  DESCRIPTION
  _bookdown.yml
  nullabor_translation_Korean.Rmd
Labels: translation

#61 rvest_data_transformation_translate
  _bookdown.yml
  resources/rvest_data_transformation_translate/cheatsheet1.jpg
  resources/rvest_data_transformation_translate/cheatsheet2.jpg
  rvest_data_transformation_translate.Rmd
Labels: translation

#125 Create Mapping_in_R.rmd
  DESCRIPTION
  Mapping_in_R.rmd
  _bookdown.yml
Labels: changes requested, maps

#87 SandDance
  SandDance.Rmd
  _bookdown.yml
Labels: video

#47 Time Series Modeling with ARIMA in R
  DESCRIPTION
  _bookdown.yml
  time_series_arima.Rmd
Labels: data viz (static)

#57 Comparative study of mosaic
  Comparative_Study_of_Mosaic.Rmd
  DESCRIPTION
  _bookdown.yml
Labels: data viz (static)

#77 googleVis community contribution 18
  DESCRIPTION
  GoogleVis_tutorial.Rmd
  _bookdown.yml
Labels: data viz (interactive)

#113 Added Ashutosh Kanitkar's Community Contribution
  NLP_Basics_with_Python.Rmd
  _bookdown.yml
Labels: python

#160 Add data_ink.rmd
  DESCRIPTION
  _bookdown.yml
  data_ink.Rmd
Labels: Other

#91 Added Kevin Womack's Contribution (Tweepy)
  Tweepy.Rmd
  _bookdown.yml
Labels: python, workshop

#82 Added community contribution work on R vs Tableau.
  DESCRIPTION
  _bookdown.yml
  r_vs_tableau_plots.Rmd
  resources/r_vs_tableau/2014_world_gdp_with_codes.csv.txt
  resources/r_vs_tableau/AirQualityUCI.csv
  resources/r_vs_tableau/Community Contribution EDAV.twbx
  resources/r_vs_tableau/air_quality_r.csv
  resources/r_vs_tableau/images/choropleth.JPG
  resources/r_vs_tableau/images/dashboard.JPG
  resources/r_vs_tableau/images/hands-on-1st-page-area-sheet.JPG
  resources/r_vs_tableau/images/snapshot.JPG
  resources/r_vs_tableau/images/story-all-together.JPG
  resources/r_vs_tableau/images/story-choropleth.JPG
  resources/r_vs_tableau/images/story-hands-on.JPG
  resources/r_vs_tableau/images/story-time-series.JPG
  resources/r_vs_tableau/images/time-series.JPG
Labels: data viz (static)

#133 add French version of edav.info
  French_version_of_edav_info.Rmd
  _bookdown.yml
Labels: translation

#97 Financial_Model_cc55
  DESCRIPTION
  Exploring_Financial_Models.Rmd
  _bookdown.yml
Labels: lightning talk

#56 Files for Regex workshop
  _bookdown.yml
  regex_workshop.Rmd
  resources/regex_workshop/RegEx_101.pdf
Labels: workshop

#132 data warngling sheet added
  _bookdown.yml
  data_wrangling_cheatsheet.Rmd
Labels: data wrangling

#108 "Ask a manager" salary survey dataset
  _bookdown.yml
  askamanager_salary_survey.Rmd
  resources/askamanager_salary_survey/Contribute-transforms.png
Labels: data wrangling

#122 translation_of_lattice_intro
  DESCRIPTION
  _bookdown.yml
  translation_of_lattice_intro.Rmd
Labels: translation

#121 adding the visualization_python_vs_r.rmd file
  _bookdown.yml
  visualization_python_vs_R.Rmd
Labels: python

#41 added Chinese_Translation_of_plotly_and_parcoords.Rmd project
  Chinese_Translation_of_plotly_and_parcoords.Rmd
  DESCRIPTION
  _bookdown.yml
Labels: translation

#128 added project: {categorical_data_cheatsheet} by Zhi Qi
  _bookdown.yml
  categorical_data_cheatsheet.Rmd
Labels: cheat sheet

#110 group 87: Rvest Cheatsheet
  Rvest_Cheatsheet.Rmd
  _bookdown.yml
Labels: bug, cheat sheet

#63 Group42_Tiffany_Zhu_Olivia_Wang
  DESCRIPTION
  _bookdown.yml
  midsemester_review.Rmd
  resources/midsemester_review/1_intro_image.png
  resources/midsemester_review/3_gg.png
  resources/midsemester_review/box1.png
  resources/midsemester_review/box2.png
  resources/midsemester_review/heatmaps.png
  resources/midsemester_review/mosaic1.png
  resources/midsemester_review/mosaic2.png
  resources/midsemester_review/mosaic3.png
  resources/midsemester_review/normal.png
  resources/midsemester_review/ridge.png
  resources/midsemester_review/timeseries.png
  resources/midsemester_review/timeseries2.png
Labels: bug, cheat sheet

#163 Basic R Tutorial from group 68 issue fixed
  _bookdown.yml
  basic_r_tutorial.Rmd
Labels: changes requested

#100 World heatmap plotly
  DESCRIPTION
  _bookdown.yml
  resources/world_heatmap/business_rankings.csv
  world_heatmap.Rmd
Labels: changes requested, maps

#104 add cheatsheet for tidyverse
  _bookdown.yml
  resources/tidyverse_tutorial/tidyverseFinal.png
  tidyverse_contribution.Rmd
Labels: changes requested, cheat sheet

#165 commit rvest package
  rvest_translation.Rmd
Labels: translation

#67 parcoords_translation
  DESCRIPTION
  _bookdown.yml
  parcoords_translation.Rmd
Labels: translation

#75 Add forcats_tutorial_translation.rmd
  DESCRIPTION
  _bookdown.yml
  forcats_tutorial_translation.Rmd
Labels: translation

#78 rmarkdown_tutorial
  _bookdown.yml
  resources/rmarkdown_tutorial/OutputExample.Rmd
  resources/rmarkdown_tutorial/headers.png
  resources/rmarkdown_tutorial/output.png
  resources/rmarkdown_tutorial/rmarkdownflow.png
  rmarkdown_tutorial.Rmd
Labels: Other, changes requested

#60 File for Yuge Shen and Shengqing Xia
  DESCRIPTION
  Multivariable_Regression_Tutorial.Rmd
  _bookdown.yml
  resources/Multivariable_Regression_Tutorial/diag.png
Labels: Other

#68 plotrix community contribution 18
  DESCRIPTION
  _bookdown.yml
  plotrix.Rmd
Labels: data viz (static)

#114 Sentiment visualization with Wordclouds
  DESCRIPTION
  _bookdown.yml
  resources/wordcloud_sentiment/reviews.csv
  resources/wordcloud_sentiment/wordcloud.png
  sentiment_with_wordcloud.Rmd
Labels: Other, changes requested

#55 Adding keras tutorial
  DESCRIPTION
  _bookdown.yml
  keras_tutorial.Rmd
Labels: Other

#143 Data visualization workshop
  Data_Visualization_Workshop.Rmd
  _bookdown.yml
Labels: changes requested, workshop

#44 pull request from cc group 47
  DESCRIPTION
  _bookdown.yml
  resources/us_map/US-State-Boundaries-Census-2014.dbf
  resources/us_map/US-State-Boundaries-Census-2014.shp
  resources/us_map/US-State-Boundaries-Census-2014.shx
  us_map.Rmd
Labels: changes requested, maps

#123 Stamen maps for spatial data
  .gitignore
  Stamen_Maps_for_Spatial_Data.Rmd
  _bookdown.yml
  _common.R
  resources/newyork_sample_collisions_data.csv
Labels: changes requested, maps

#40 Adding the tutorial "Running Python in R Markdown"
  DESCRIPTION
  _bookdown.yml
  python_r_markdown.Rmd
Labels: Other, changes requested

#134 CC Assignment Submission
  VideoInterviews.Rmd
Labels: changes requested, video
